name: Merge Main into Dev

on:
  push:
    branches:
      - main

jobs:
  merge_main_dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge main into dev
        run: |
          git config --global user.email "your_email@example.com"
          git config --global user.name "Your Name"
          git fetch origin dev:dev
          git checkout dev
          git merge main --no-edit
          git push origin dev

