name: Merge dev to main

on:
  push:
    branches:
      - main
      - dev

jobs:
  merge_dev_to_main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Merge dev into temp branch
        run: git checkout -b temp && git merge dev

      - name: Run tests
        run: |
          # Run your tests here
          # If tests fail, exit with a non-zero exit code to halt the workflow

      - name: Merge temp branch into main
        run: git checkout main && git merge temp

      - name: Push changes to main
        run: git push origin main
