name: Merge Main into dev

on:
  pull_request:
    types: merge dev

env:
  DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}

jobs:
  main:
    if: ${{ github.event.label.name == 'merge main' }}
    name: Merge Main
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: perform merge
        run: |
          git config --global user.email "deepanpradeep407@gmail.com"
          git config --global user.name "deepanpradeep@users.noreply.github.com"
          git status
          git pull
          git checkout "$dev_branch"
          git status
          git checkout "$main_branch"
          git merge "$dev_branch" --no-edit
          git push
          git status

      - name: remove label
        if: always()
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: merge main
