name: Merge Dev README into Main

on:
  push:
    branches: 
      - dev

jobs:
  merge_readme:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      
    - name: Merge README
      run: |
        # Example script to merge README files
        # Read contents of dev README
        DEV_README=$(cat dev/README.md)
        # Append dev README contents to main README
        echo "$DEV_README" >> main/README.md
        # Commit changes
        git add main/README.md
        git commit -m "Merge dev README into main"
        # Push changes
        git push origin main
