name: Merge README Files

on:
  push:
    branches:
      - main

jobs:
  merge_readme_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Merge dev README into main
      run: |
        git fetch origin
        git checkout -b temp-branch origin/dev
        git merge main --no-commit --no-ff
        git checkout main -- README.md
        git commit -m "Merge dev README into main"
        git push origin main
