name: Merge Main into Dev and Update README

on:
  push:
    branches: 
      - main

jobs:
  merge_main_dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge main into dev
        run: |
          git config --global user.email "deepanpradeep406@gmail.com"
          git config --global user.name "deepanpradeep"
          git fetch origin dev:dev
          git checkout dev
          git merge main --no-edit
          git push origin dev

      - name: Update README
        run: |
          echo "### Merge Main into Dev" >> README.md
          echo "This README file was automatically updated to reflect the merge of changes from the main branch into the dev branch." >> README.md
          git add README.md
          git commit -m "Update README after merging main into dev" || true
          git push origin dev
